# Generated by Django 3.2.7 on 2021-10-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('NO_FILTER', 'no filter'), ('NEGATIVE', 'negative'), ('GREYSCALE', 'greyscale'), ('BRIGHTENING', 'brightening'), ('ARITMETIKA', 'aritmetika'), ('BOOLEAN', 'boolean'), ('GEOMETRI', 'geometri')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
